services:
  - type: web
    name: django-ocr-app
    rootDirectory: myproject
    env: docker
    plan: free  # Change to 'starter' or 'standard' if needed
    dockerfilePath: myproject/Dockerfile
    autoDeploy: true  # Enables Auto-Deploy on Git Push
