# Generated by Django 5.1.6 on 2025-03-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='image',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
